<template>
	<div>
		<h5>Пользовательское соглашение</h5>
		<hr>


<div class="row">
          <div class="col-12 col-md-12">

            <!-- Text -->
            <p class="fs-lg text-gray-800 mb-6 mb-md-8">
                </p><p class="fs-lg text-gray-800 mb-6 mb-md-8"></p><h3 class="mb-5"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">1. Сторона сделки.</font></font></h3><p></p>
				<p class="fs-lg text-gray-800 mb-6 mb-md-8"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Договор заключается между Интернет-сервисом по обмену титульных знаков, именуемым в дальнейшем Исполнителем, с одной стороны, и Заказчиком в лице того, кто воспользовался услугами Исполнителя, с другой стороны.</font></font></p>
				<p class="fs-lg text-gray-800 mb-6 mb-md-8"></p><h3 class="mb-5"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">2. Список терминов.</font></font></h3><p></p>
				<p class="fs-lg text-gray-800 mb-6 mb-md-8"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">2.1. </font><font style="vertical-align: inherit;">Обмен титульных знаков – автоматизированный интернет-сервисный продукт, предоставляемый Исполнителем на основании настоящих правил.</font></font></p>
				<p class="fs-lg text-gray-800 mb-6 mb-md-8"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">2.2. </font><font style="vertical-align: inherit;">Заказчик – физическое лицо, согласившееся с условиями Исполнителя и настоящим договором, к которому он присоединяется.</font></font></p>
				<p class="fs-lg text-gray-800 mb-6 mb-md-8"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">2.3. </font><font style="vertical-align: inherit;">Титульный знак является условной единицей конкретной платежной системы, которая соответствует расчетам электронных систем и указывает на объем прав, соответствующий договору между электронной платежной системой и ее Клиентом.</font></font></p>
				<p class="fs-lg text-gray-800 mb-6 mb-md-8"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">2.4. </font><font style="vertical-align: inherit;">Заявка - информация, передаваемая Заказчиком для использования средств Исполнителя в электронной форме и свидетельствующая о том, что он принимает условия использования услуги, которые предлагаются Исполнителем в данной заявке.</font></font></p>
				<p class="fs-lg text-gray-800 mb-6 mb-md-8"></p><h3 class="mb-5"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">3. Условия соглашения.</font></font></h3><p></p>
				<p class="fs-lg text-gray-800 mb-6 mb-md-8"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Эти правила являются одними из организованных условий оферты, которые могут быть предоставлены заказчиком из основных условий настоящего договора. </font><font style="vertical-align: inherit;">Исполнители представлены публичной офертой, поставлены задачи по информированию об условиях. </font><font style="vertical-align: inherit;">Основным компилятором публичных предложений являются действия, совершенные в результате исполнения заявки Заказчиком и обещающие о его точных намерениях реализации на условиях, предложенных Исполнителем до завершения этой заявки. </font><font style="vertical-align: inherit;">Время, дата и проверка заражения осуществляется Исполнителем автоматически в момент завершения формирования настоящей заявки. </font><font style="vertical-align: inherit;">Оферта должна быть принята Заказчиком в течение 24 часов с момента окончания формирования заявки. </font><font style="vertical-align: inherit;">Договор на оказание услуг вступает в силу с почтовых отправлений. </font><font style="vertical-align: inherit;">Операции с королевскими марками учитываются в соответствии с правилами, регламентами и форматами электронных расчетных систем. </font><font style="vertical-align: inherit;">Соглашение, действительное в течение определенного срока, который составляется с момента подачи заявления о расторжении по инициативе стороны.</font></font></p>
				<p class="fs-lg text-gray-800 mb-6 mb-md-8"></p><h3 class="mb-5"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">4. Предмет договора</font></font></h3><p></p>
				<p class="fs-lg text-gray-800 mb-6 mb-md-8"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Используя технические методы, Исполнитель обязуется осуществить обмен титульных знаков за комиссию Заказчика, после подачи этим лицом заявки и делает это путем продажи титульных знаков лицам, желающим приобрести их на указанную сумму. не ниже, чем в заявке, поданной Заказчиком. </font><font style="vertical-align: inherit;">Исполнитель обязуется перечислить денежные средства на реквизиты, указанные Заказчиком. </font><font style="vertical-align: inherit;">В случае получения прибыли при обмене она остается на счету Исполнителя в качестве дополнительной выгоды и надбавки за комиссионные услуги.</font></font></p>
				<p class="fs-lg text-gray-800 mb-6 mb-md-8"></p><h3 class="mb-5"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">5. Кроме того</font></font></h3><p></p>
				<p class="fs-lg text-gray-800 mb-6 mb-md-8"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">5.1. </font><font style="vertical-align: inherit;">В случае поступления на счет Исполнителя суммы, отличной от указанной в заявке, Исполнитель производит перерасчет, соответствующий фактическому поступлению титульных знаков. </font><font style="vertical-align: inherit;">Если эта сумма превышает сумму, указанную в заявке, более чем на 10%, Исполнитель расторгает договор в одностороннем порядке и все денежные средства возвращаются на реквизиты Заказчика с учетом суммы, удержанной на комиссионные расходы при переводе.</font></font></p>
				<p class="fs-lg text-gray-800 mb-6 mb-md-8"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">5.2. </font><font style="vertical-align: inherit;">В случае, если титульные знаки не будут отправлены Исполнителем на указанные реквизиты Заказчика в течение 24 часов, Заказчик имеет полное право потребовать расторжения договора и аннулировать свою заявку, тем самым вернув титульные знаки на свой счет в полный. </font><font style="vertical-align: inherit;">Заявление о расторжении договора и возврате титульных знаков осуществляется Исполнителем в случае, если денежные средства еще не были переведены на указанные реквизиты Заказчика. </font><font style="vertical-align: inherit;">В случае расторжения договора возврат электронной валюты производится в течение 24 часов с момента получения запроса на расторжение договора. </font><font style="vertical-align: inherit;">Если задержки в возврате произошли не по вине Исполнителя, он не несет за них ответственности.</font></font></p>
				<p class="fs-lg text-gray-800 mb-6 mb-md-8"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">5.3. </font><font style="vertical-align: inherit;">В случае не поступления титульных знаков от Заказчика на счет Исполнителя в указанный срок, с момента подачи заявки Заказчиком, договор между сторонами расторгается Исполнителем с одной стороны, поскольку договор не вступает в силу. </font><font style="vertical-align: inherit;">Заказчик может быть об этом не уведомлен. </font><font style="vertical-align: inherit;">Если титульные знаки поступают на реквизиты Исполнителя по истечении указанного срока, то такие денежные средства переводятся обратно на счет Заказчика, и из этих средств удерживаются все комиссионные расходы, связанные с переводом.</font></font></p>
				<p class="fs-lg text-gray-800 mb-6 mb-md-8"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">5.4. </font><font style="vertical-align: inherit;">В случае задержки зачисления денежных средств на реквизиты, указанные Заказчиком, по вине расчетной системы, Исполнитель не несет ответственности за ущерб, возникший в результате длительного поступления денежных средств. </font><font style="vertical-align: inherit;">В этом случае Заказчик должен согласиться с тем, что все претензии будут предъявляться к системе взаиморасчетов, а Исполнитель обязуется оказывать ему содействие в меру своих возможностей в рамках закона.</font></font></p>
				<p class="fs-lg text-gray-800 mb-6 mb-md-8"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">5.5. </font><font style="vertical-align: inherit;">В случае обнаружения подделки коммуникационных потоков или оказания воздействия с целью ухудшения работы Исполнителя, а именно его программного кода, действие заявки приостанавливается, а перечисленные средства подлежат перерасчету в соответствии с действующим договором . </font><font style="vertical-align: inherit;">Если Заказчик не согласен с перерасчетом, он имеет полное право расторгнуть договор и титульные знаки будут отправлены на реквизиты, указанные Заказчиком.</font></font></p>
				<p class="fs-lg text-gray-800 mb-6 mb-md-8"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">5.6. </font><font style="vertical-align: inherit;">В случае использования услуг Исполнителя Заказчик полностью соглашается с тем, что Исполнитель несет ограниченную ответственность в соответствии с рамками настоящих правил за полученные титульные знаки и не дает дополнительных гарантий Заказчику, а также не несет дополнительных ответственность перед ним. </font><font style="vertical-align: inherit;">Соответственно, Заказчик не несет никакой дополнительной ответственности перед Исполнителем.</font></font></p>
				<p class="fs-lg text-gray-800 mb-6 mb-md-8"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">5.7. </font><font style="vertical-align: inherit;">Заказчик обязуется соблюдать соответствующие законодательству нормы, а также не подделывать потоки связи и не создавать препятствий для нормальной работы программного кода Исполнителя.</font></font></p>
				<p class="fs-lg text-gray-800 mb-6 mb-md-8"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">5.8. </font><font style="vertical-align: inherit;">Исполнитель не несет ответственности за убытки и последствия в случае ошибочного перевода электронной валюты в случае, если Заказчик указал неверные реквизиты при подаче заявки.</font></font></p>
				<p class="fs-lg text-gray-800 mb-6 mb-md-8"></p><h3 class="mb-5"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">6. Гарантийный срок</font></font></h3><p></p>
				<p class="fs-lg text-gray-800 mb-6 mb-md-8"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">В течение 24 часов с момента оформления обмена титульных знаков Исполнитель предоставляет гарантию на оказанные услуги, если не указано иное. </font><font style="vertical-align: inherit;">если вы требуете возмещения до 500 долларов США, вы должны предоставить видеоподтверждение.</font></font></p>
				<p class="fs-lg text-gray-800 mb-6 mb-md-8"></p><h3 class="mb-5"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">7. Невидимые обстоятельства</font></font></h3><p></p>
				<p class="fs-lg text-gray-800 mb-6 mb-md-8"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">В случае возникновения в процессе обработки заявки Заказчика непредвиденных обстоятельств, способствующих невыполнению Исполнителем условий договора, сроки исполнения заявки переносятся на соответствующий период действия обстоятельств непреодолимой силы. </font><font style="vertical-align: inherit;">Исполнитель не несет ответственности за просроченные обязательства. </font><font style="vertical-align: inherit;">Если вы хотите претендовать на возврат, вам необходимо подать заявку на обмен на ту сумму, а не на меньшую сумму средств, которая требуется для возврата.</font></font></p>
				<p class="fs-lg text-gray-800 mb-6 mb-md-8"></p><h3 class="mb-5"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">8. Форма договора.</font></font></h3><p></p>
				<p class="fs-lg text-gray-800 mb-6 mb-md-8"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Обе стороны в лице Исполнителя и Заказчика принимают настоящий договор как договор равной юридической силы, указанный в письменной форме.</font></font></p>
				<p class="fs-lg text-gray-800 mb-6 mb-md-8"></p><h3 class="mb-5"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">9. Получение клиентом денежных средств после их заморозки</font></font></h3><p></p>
				<p class="fs-lg text-gray-800 mb-6 mb-md-8"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Зеркальная транзакция — это единственный доступный для клиента способ получить средства после того, как они были заморожены. </font><font style="vertical-align: inherit;">Для предотвращения замораживания - транзакций необходимо соблюдать правила.</font></font></p>
				<p class="fs-lg text-gray-800 mb-6 mb-md-8"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">9.1 Соблюдать комиссии для совершения обмена.</font></font></p>
				<p class="fs-lg text-gray-800 mb-6 mb-md-8"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">9.2 Правильные данные квитанции.</font></font></p>
				<p class="fs-lg text-gray-800 mb-6 mb-md-8"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">9.3 Конверсионные монеты правильные.</font></font></p>
				<p class="fs-lg text-gray-800 mb-6 mb-md-8"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">9.4 При конвертации суммы более $1000 (одной тысячи долларов) необходимо вручную учитывать комиссию обменного пункта.</font></font></p>
				<p class="fs-lg text-gray-800 mb-6 mb-md-8"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Если клиент совершил вышеуказанную ошибку, средства будут заморожены. </font><font style="vertical-align: inherit;">Для разблокировки необходимо совершить зеркальную транзакцию, соблюдая правила обменного пункта.</font></font></p>
				<p class="fs-lg text-gray-800 mb-6 mb-md-8"></p><h3 class="mb-5"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">10 Претензии и споры</font></font></h3><p></p>
				<p class="fs-lg text-gray-800 mb-6 mb-md-8"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Претензии по настоящему договору принимаются Исполнителем в форме электронного письма, в котором Заказчик указывает суть претензии. </font><font style="vertical-align: inherit;">Данное письмо направляется на реквизиты Исполнителя, указанные на сайте.</font></font></p>
				<p class="fs-lg text-gray-800 mb-6 mb-md-8"></p><h3 class="mb-5"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">11. Проведение обменных операций.</font></font></h3> <p></p>
				<p class="fs-lg text-gray-800 mb-6 mb-md-8"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">11.1. </font><font style="vertical-align: inherit;">Категорически запрещается использовать услуги Исполнителя для незаконных переводов и мошеннических действий. </font><font style="vertical-align: inherit;">При заключении настоящего договора Заказчик обязуется соблюдать данные требования и в случае мошенничества нести уголовную ответственность, установленную законодательством на данный момент.</font></font></p>
				<p class="fs-lg text-gray-800 mb-6 mb-md-8"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">11.2. </font><font style="vertical-align: inherit;">В случае невозможности выполнения заявки автоматически, по независящим от Исполнителя обстоятельствам, таким как отсутствие связи, нехватка средств или ошибочные данные Заказчика, денежные средства зачисляются на счет в течение ближайших 24 часов или возвращается на реквизиты Заказчика за вычетом комиссионных расходов.</font></font></p>
				<p class="fs-lg text-gray-800 mb-6 mb-md-8"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">11.3. </font><font style="vertical-align: inherit;">По первому требованию Исполнитель вправе передать информацию о переводе электронной валюты правоохранительным органам, администрации расчетных систем, а также пострадавшим от неправомерных действий, пострадавшим от мошенничества, доказанного судебными органами.</font></font></p>
				<p class="fs-lg text-gray-800 mb-6 mb-md-8"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">11.4. </font><font style="vertical-align: inherit;">Заказчик обязуется предоставить все документы, удостоверяющие его личность, в случае подозрения в мошенничестве и отмывании денег.</font></font></p>
				<p class="fs-lg text-gray-800 mb-6 mb-md-8"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">11.5. </font><font style="vertical-align: inherit;">Заказчик обязуется не вмешиваться в работу Исполнителя и не повреждать его программное и аппаратное обеспечение, а Заказчик обязуется передавать достоверную информацию для обеспечения выполнения Исполнителем всех условий договора.</font></font></p>
				<p class="fs-lg text-gray-800 mb-6 mb-md-8"></p><h3 class="mb-5"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">12. Отказ от ответственности.</font></font></h3><p></p>
				<p class="fs-lg text-gray-800"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Исполнитель вправе отказаться от заключения договора и выполнения заявки, причем без объяснения причин. </font><font style="vertical-align: inherit;">Этот пункт относится к любому клиенту.</font></font></p>
            <p></p>
          </div>
        </div>


	</div>
</template>